int BLOB_MIN_RADIUS = 20;
int BLOB_MAX_RADIUS = 70;
int BLOB_MIN_NUMBER = 10;
int BLOB_MAX_NUMBER = 20;
float BLOB_RADIUS_SPEED_RATIO = 275;
float BLOB_START_HEALTH = 220;
float BLOB_REPRODUCE_HEALTH = 275;

int FOOD_MIN_SIDE = 10;
int FOOD_MAX_SIDE = 25;
int FOOD_MIN_NUMBER = 10;
int FOOD_MAX_NUMBER = 25; 
float FOOD_MASS_ENERGY_RATIO = 20;
